export const categories = [
    { title: "Accountancy", count: 0 },
    { title: "Administration", count: 0 },
    { title: "Aerospace", count: 0 },
    { title: "Agribusiness", count: 1 },
    { title: "Agriculture", count: 1 },
    { title: "Auditing", count: 0 },
    { title: "Automotive", count: 3 },
    { title: "Banking And Financial Services", count: 5 },
    { title: "Bio-tech And Chemical", count: 0 },
    { title: "Business Management", count: 0 },
    { title: "Chemical Industry", count: 0 },
    { title: "Clearing", count: 0 },
    { title: "Communication", count: 1 },
    { title: "Construction And Architectural", count: 0 },
    { title: "Consultancy", count: 0 },
    { title: "Creative/Design/Clothing", count: 0 },
    { title: "Education", count: 0 },
    { title: "Electrical And Electronics", count: 2 },
    { title: "Electricity", count: 0 },
    { title: "Entertainment", count: 0 },
    { title: "Environment", count: 0 },
    { title: "Estate", count: 0 },
    { title: "Facility", count: 0 },
    { title: "Fishery", count: 0 },
    { title: "Food And Beverages", count: 2 },
    { title: "Forestry", count: 0 },
    { title: "Furniture", count: 0 },
    { title: "Hospital/Health Care", count: 2 },
    { title: "Hospitality", count: 5 },
    { title: "Hr", count: 0 },
    { title: "Human Resources", count: 0 },
    { title: "International Affairs/Diplomacy", count: 0 },
    { title: "It/Technology", count: 0 },
    { title: "Journalism/Journalism/Media", count: 0 },
    { title: "land", count: 0 },
    { title: "Legal/Law", count: 0 },
    { title: "Logistics", count: 1 },
    { title: "Logistics/Transportation", count: 0 },
    { title: "Manufacturing", count: 14 },
    { title: "Maritime", count: 0 },
    { title: "Market Research And Exploration", count: 0 },
    { title: "Mechanical Engineering", count: 0 },
    { title: "Mining", count: 7 },
    { title: "Muhimbili", count: 0 },
    { title: "NGO/CBO/IOG/Project", count: 13 },
    { title: "Oil/ Gas", count: 0 },
    { title: "Pharmaceutics", count: 0 },
    { title: "Procurement", count: 0 },
    { title: "Psychology", count: 0 },
    { title: "Public Services", count: 0 },
    { title: "records", count: 0 },
    { title: "Research And Scientific", count: 0 },
    { title: "Robotics", count: 0 },
    { title: "Sales And Marketing", count: 0 },
    { title: "Security And Defence", count: 0 },
    { title: "Service", count: 1 },
    { title: "Social And Medical Services", count: 0 },
    { title: "Social Work", count: 0 },
    { title: "Solar And Green Energy", count: 0 },
    { title: "Sports And Bet", count: 0 },
    { title: "Tax", count: 0 },
    { title: "TCC", count: 0 },
    { title: "Telecommunication", count: 1 },
    { title: "Trade/Retail/Wholesales/Commerce", count: 1 },
    { title: "Transportation", count: 1 },
    { title: "Travel And Tourism", count: 0 }
];

export const companies =  [
    { title: "Exact Manpower Consulting Ltd", count: 17 },
    { title: "Natural Extracts Industries Ltd", count: 0 },
    { title: "Touch Foundation Tanzania", count: 0 }
];

export const locations = [
    { title: "Dodoma", count: 5 },
    { title: "Tanga", count: 0 },
    { title: "Mbeya", count: 1 },
    { title: "Kigoma", count: 2 },
    { title: "Iringa", count: 0 },
    { title: "Mtwara", count: 0 },
    { title: "Rukwa", count: 0 },
    { title: "Singida", count: 0 },
    { title: "Kilimanjaro", count: 0 },
    { title: "Arusha", count: 3 },
    { title: "Geita", count: 0 },
    { title: "Kagera", count: 0 },
    { title: "Katavi", count: 0 },
    { title: "Lindi", count: 0 },
    { title: "Manyara", count: 0 },
    { title: "Morogoro", count: 5 },
    { title: "Mwanza", count: 1 },
    { title: "Njombe", count: 0 },
    { title: "Ruvuma", count: 0 },
    { title: "Shinyanga", count: 5 },
    { title: "Simiyu", count: 0 },
    { title: "Songea", count: 0 },
    { title: "Songwe", count: 0 },
    { title: "Tabora", count: 0 },
    { title: "Unguja North", count: 0 },
    { title: "Unguja South", count: 0 },
    { title: "Pemba North", count: 0 },
    { title: "Pemba South", count: 0 },
    { title: "Nairobi", count: 0 },
    { title: "Mombasa", count: 0 },
    { title: "Amuria", count: 0 },
    { title: "Budaka", count: 0 },
    { title: "Bududa", count: 0 },
    { title: "Bugiri", count: 0 },
    { title: "Bugweri", count: 0 },
    { title: "Bukedea", count: 0 },
    { title: "Bukwo", count: 0 },
    { title: "Bulambuli", count: 0 },
    { title: "Kisumu", count: 0 },
    { title: "Kwale", count: 0 },
    { title: "Kilifi", count: 0 },
    { title: "Tana River", count: 0 },
    { title: "Taita-Taveta", count: 0 },
    { title: "Dar Es Salaam", count: 47 },
    { title: "mara", count: 3 },
    { title: "pwani", count: 0 },
    { title: "Mafia", count: 0 },
    { title: "Lusaka", count: 0 },
    { title: "Select regions", count: 0 },
    { title: "Dar", count: 0 },
    { title: "GUJARAT", count: 0 },
    { title: "CHENNAI", count: 0 },
    { title: "Matabeleland", count: 0 },
    { title: "47", count: 0 },
    { title: "Zanzibar", count: 2 },
    { title: "Accra", count: 0 },
    { title: "Dar Es Salaam", count: 1 }
];
